# تسجيل حساب
document.getElementById("registerForm")?.addEventListener("submit",function(e){e.preventDefault();const username=document.getElementById("username").value;const email=document.getElementById("email").value;const password=document.getElementById("password").value;const users=JSON.parse(localStorage.getItem("users")||"[]");if(users.find(u=>u.email===email)){alert("هذا البريد مستخدم مسبقاً");return;}users.push({username,email,password});localStorage.setItem("users",JSON.stringify(users));alert("تم التسجيل بنجاح");window.location.href="login.html"});
// تسجيل دخول
document.getElementById("loginForm")?.addEventListener("submit",function(e){e.preventDefault();const email=document.getElementById("loginEmail").value;const password=document.getElementById("loginPassword").value;const users=JSON.parse(localStorage.getItem("users")||"[]");const user=users.find(u=>u.email===email&&u.password===password);if(!user){alert("خطأ في البريد أو كلمة المرور");return;}localStorage.setItem("currentUser",JSON.stringify(user));window.location.href="order.html"});
// عرض بيانات المستخدم
window.addEventListener("load",function(){const user=JSON.parse(localStorage.getItem("currentUser")||"null");if(document.getElementById("orderName")){if(!user){window.location.href="login.html";return;}document.getElementById("orderName").value=user.username;document.getElementById("orderEmail").value=user.email}});
// تسجيل خروج
document.getElementById("logoutBtn")?.addEventListener("click",function(){localStorage.removeItem("currentUser");window.location.href="login.html"});
// فاتورة تفاعلية
const serviceSelect=document.getElementById("serviceSelect");const quantitySelect=document.getElementById("quantitySelect");const invoice=document.getElementById("invoice");const invoiceDetails=document.getElementById("invoiceDetails");const invTotal=document.getElementById("invTotal");const servicePrices={"فيسبوك متابعين":0.007,"إنستغرام مشاهدات":0.0006,"TikTok مشاهدات":0.0006,"باقة كاملة":0.03};function updateInvoice(){const service=serviceSelect?.value;const quantity=parseInt(quantitySelect?.value)||0;if(!service||quantity<=0){invoice.style.display="none";return;}let total=0;invoiceDetails.innerHTML="";if(service==="باقة كاملة"){for(let key in servicePrices){if(key==="باقة كاملة")continue;let line=servicePrices[key]*quantity;total+=line;invoiceDetails.innerHTML+=`<p>${key}: ${servicePrices[key].toFixed(4)} × ${quantity} = ${line.toFixed(4)} USDT</p>`;}}else{let line=servicePrices[service]*quantity;total=line;invoiceDetails.innerHTML=`<p>${service}: ${servicePrices[service].toFixed(4)} × ${quantity} = ${line.toFixed(4)} USDT</p>`;}invTotal.innerText=total.toFixed(4);invoice.style.display="block"}serviceSelect?.addEventListener("change",updateInvoice);quantitySelect?.addEventListener("change",updateInvoice);
// نسخ Binance
function copyBinance(){const id=document.getElementById("binanceId")?.innerText;navigator.clipboard.writeText(id);alert("تم نسخ Binance ID: "+id);}